#!/usr/bin/env python3
# Exports the curated answer banks to website/answers.js (window.ANSWERS_DATA).
# Used by Practice Mode + Mastery views. Run AFTER regenerating the banks.
#   cd platform-engineering && python3 scripts/export_answers_js.py
import ast, json, os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SCRIPTS = os.path.join(ROOT, 'scripts')
WEBSITE = os.path.join(ROOT, 'website')

SOURCES = ['gen_answer_bank_a.py', 'ans_bank_b1.py', 'ans_bank_b2.py', 'ans_bank_b3.py']


def extract_answers(path):
    src = open(path, encoding='utf-8').read()
    tree = ast.parse(src)
    for node in tree.body:
        if isinstance(node, ast.Assign):
            for t in node.targets:
                if isinstance(t, ast.Name) and t.id == 'ANSWERS':
                    return ast.literal_eval(node.value)
    raise RuntimeError(f'no ANSWERS in {path}')


def main():
    merged = {}
    for f in SOURCES:
        d = extract_answers(os.path.join(SCRIPTS, f))
        for mid, entries in d.items():
            out = []
            for tup in entries:
                q = tup[0]
                a = tup[1]
                r = tup[2]
                w = tup[3] if len(tup) > 3 and tup[3] else f"Asked in {mid} — verify against the module's checklist and research."
                out.append({'q': q, 'a': a, 'r': r, 'w': w})
            merged[mid] = out

    total = sum(len(v) for v in merged.values())
    payload = '/* Auto-generated by scripts/export_answers_js.py — do not edit.\n'
    payload += '   Source: gen_answer_bank_a.py + ans_bank_b1/b2/b3.py (curated answers). */\n'
    payload += 'window.ANSWERS_DATA = ' + json.dumps(merged, ensure_ascii=False) + ';\n'

    out_path = os.path.join(WEBSITE, 'answers.js')
    open(out_path, 'w', encoding='utf-8').write(payload)
    print(f'answers.js written: {total} answers across {len(merged)} modules')


if __name__ == '__main__':
    main()
